install docker-ce-rootless-extras explicitly + unrecommend `sudo usermod -aG docker me`
docker/docker-install pull request #215
Opened 2021-02-15 03:29 UTC by AkihiroSuda

- install.sh: install docker-ce-rootless-extras explicitly

Fix #212

- install.sh: promote Rootless mode over "sudo usermod -aG docker me"

Fix #210

2021-02-24 04:28 UTC, AkihiroSuda commented
@thaJeztah @tianon @tiborvass @tonistiigi PTAL?

2021-02-25 10:54 UTC, thaJeztah requested changes

2021-02-25 10:54 UTC, thaJeztah commented on install.sh
> +		echo "For more information about Rootless mode, refer to https://docs.docker.com/engine/security/rootless/"
Have some other suggestions, but let me open a PR against your branch, that's probably easier 😅

2021-02-25 10:57 UTC, thaJeztah commented
Opened https://github.com/AkihiroSuda/docker-install/pull/2 against your fork with suggestions 🤗

2021-02-25 11:16 UTC, AkihiroSuda commented
Thanks, merged https://github.com/AkihiroSuda/docker-install/pull/2

2021-02-25 11:44 UTC, thaJeztah approved these changes
LGTM

@tiborvass @StefanScherer ptal

2021-02-25 12:48 UTC, StefanScherer approved these changes
LGTM ❤️

2021-02-25 13:01 UTC, thaJeztah commented
We can merge this after https://github.com/docker/docker.github.io/pull/12387 is merged (which makes the new redirects go live on docs.docker.com)

2021-02-25 14:11 UTC, thaJeztah commented
Tested the script on Ubuntu 20.10, and install was successfully, so going ahead and merge this one

2021-02-25 14:11 UTC, merged