fix: add apparmor-utils to install prereqs
docker/docker-install pull request #333
Opened 2023-02-02 14:30 UTC by dvdksn

Adds apparmor-utils as a prereq dependency

Solves issues for some Debian users on version 23.0

2023-02-02 15:06 UTC, vvoland approved these changes

2023-02-02 15:13 UTC, neersighted requested changes
I don't think this change should be accepted. `apparmor-utils` is an optional dependency we are meant to check at runtime, and this entire issue happened because containerd regressed their public API and we did not catch it. I think that a release note is likely adequate for now, as altering the semantics of the installer to work around a minor regression is likely to be painful later (and many users will not want apparmor!).

2023-02-02 16:53 UTC, akerouanton commented
`apparmor_parser` comes from package `apparmor`, not `apparmor-utils` (see [here](https://packages.debian.org/search?searchon=contents&keywords=apparmor_parser&mode=path&suite=stable&arch=any)). This package is included by default in bullseye cloud images (see [here](https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.json)). Thus, users have to intentionally uninstall it to face the reported bug. So I second what @neersighted said: the issue is in moby/moby or containerd, not in the install script.

2023-02-03 09:11 UTC, thaJeztah commented
I opened https://github.com/docker/docker-install/pull/335 to remove the `--no-install-recommends` flag instead.

2023-02-03 09:13 UTC, closed without merging